version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - backend_network
      - frontend_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend_network

volumes:
  mongodb_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
